//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.312.
// 
#pragma warning disable 1591

namespace TerraViewer.us.geocoder {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeoCode_Binding", Namespace="http://rpc.geocoder.us/Geo/Coder/US/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(GeocoderIntersectionResult))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(GeocoderAddressResult))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(GeocoderResult))]
    public partial class GeoCode_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback geocodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback geocode_addressOperationCompleted;
        
        private System.Threading.SendOrPostCallback geocode_intersectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GeoCode_Service() {
            this.Url = global::TerraViewer.Properties.Settings.Default.WWTExplorer_us_geocoder_GeoCode_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event geocodeCompletedEventHandler geocodeCompleted;
        
        /// <remarks/>
        public event geocode_addressCompletedEventHandler geocode_addressCompleted;
        
        /// <remarks/>
        public event geocode_intersectionCompletedEventHandler geocode_intersectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://rpc.geocoder.us/Geo/Coder/US#geocode", RequestNamespace="http://rpc.geocoder.us/Geo/Coder/US/", ResponseNamespace="http://rpc.geocoder.us/Geo/Coder/US/")]
        [return: System.Xml.Serialization.SoapElementAttribute("results")]
        public GeocoderResult[] geocode(string location) {
            object[] results = this.Invoke("geocode", new object[] {
                        location});
            return ((GeocoderResult[])(results[0]));
        }
        
        /// <remarks/>
        public void geocodeAsync(string location) {
            this.geocodeAsync(location, null);
        }
        
        /// <remarks/>
        public void geocodeAsync(string location, object userState) {
            if ((this.geocodeOperationCompleted == null)) {
                this.geocodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngeocodeOperationCompleted);
            }
            this.InvokeAsync("geocode", new object[] {
                        location}, this.geocodeOperationCompleted, userState);
        }
        
        private void OngeocodeOperationCompleted(object arg) {
            if ((this.geocodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.geocodeCompleted(this, new geocodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://rpc.geocoder.us/Geo/Coder/US#geocode_address", RequestNamespace="http://rpc.geocoder.us/Geo/Coder/US/", ResponseNamespace="http://rpc.geocoder.us/Geo/Coder/US/")]
        [return: System.Xml.Serialization.SoapElementAttribute("results")]
        public GeocoderAddressResult[] geocode_address(string address) {
            object[] results = this.Invoke("geocode_address", new object[] {
                        address});
            return ((GeocoderAddressResult[])(results[0]));
        }
        
        /// <remarks/>
        public void geocode_addressAsync(string address) {
            this.geocode_addressAsync(address, null);
        }
        
        /// <remarks/>
        public void geocode_addressAsync(string address, object userState) {
            if ((this.geocode_addressOperationCompleted == null)) {
                this.geocode_addressOperationCompleted = new System.Threading.SendOrPostCallback(this.Ongeocode_addressOperationCompleted);
            }
            this.InvokeAsync("geocode_address", new object[] {
                        address}, this.geocode_addressOperationCompleted, userState);
        }
        
        private void Ongeocode_addressOperationCompleted(object arg) {
            if ((this.geocode_addressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.geocode_addressCompleted(this, new geocode_addressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://rpc.geocoder.us/Geo/Coder/US#geocode_intersection", RequestNamespace="http://rpc.geocoder.us/Geo/Coder/US/", ResponseNamespace="http://rpc.geocoder.us/Geo/Coder/US/")]
        [return: System.Xml.Serialization.SoapElementAttribute("results")]
        public GeocoderIntersectionResult[] geocode_intersection(string intersection) {
            object[] results = this.Invoke("geocode_intersection", new object[] {
                        intersection});
            return ((GeocoderIntersectionResult[])(results[0]));
        }
        
        /// <remarks/>
        public void geocode_intersectionAsync(string intersection) {
            this.geocode_intersectionAsync(intersection, null);
        }
        
        /// <remarks/>
        public void geocode_intersectionAsync(string intersection, object userState) {
            if ((this.geocode_intersectionOperationCompleted == null)) {
                this.geocode_intersectionOperationCompleted = new System.Threading.SendOrPostCallback(this.Ongeocode_intersectionOperationCompleted);
            }
            this.InvokeAsync("geocode_intersection", new object[] {
                        intersection}, this.geocode_intersectionOperationCompleted, userState);
        }
        
        private void Ongeocode_intersectionOperationCompleted(object arg) {
            if ((this.geocode_intersectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.geocode_intersectionCompleted(this, new geocode_intersectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.geocoder.us/Geo/Coder/US/")]
    public partial class GeocoderResult {
        
        private int zipField;
        
        private string stateField;
        
        private string cityField;
        
        private float latField;
        
        private float longField;
        
        private int numberField;
        
        private string suffixField;
        
        private string prefixField;
        
        private string typeField;
        
        private string streetField;
        
        private string suffix1Field;
        
        private string prefix1Field;
        
        private string type1Field;
        
        private string street1Field;
        
        private string suffix2Field;
        
        private string prefix2Field;
        
        private string type2Field;
        
        private string street2Field;
        
        /// <remarks/>
        public int zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public float lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public float @long {
            get {
                return this.longField;
            }
            set {
                this.longField = value;
            }
        }
        
        /// <remarks/>
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string suffix1 {
            get {
                return this.suffix1Field;
            }
            set {
                this.suffix1Field = value;
            }
        }
        
        /// <remarks/>
        public string prefix1 {
            get {
                return this.prefix1Field;
            }
            set {
                this.prefix1Field = value;
            }
        }
        
        /// <remarks/>
        public string type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
            }
        }
        
        /// <remarks/>
        public string street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        public string suffix2 {
            get {
                return this.suffix2Field;
            }
            set {
                this.suffix2Field = value;
            }
        }
        
        /// <remarks/>
        public string prefix2 {
            get {
                return this.prefix2Field;
            }
            set {
                this.prefix2Field = value;
            }
        }
        
        /// <remarks/>
        public string type2 {
            get {
                return this.type2Field;
            }
            set {
                this.type2Field = value;
            }
        }
        
        /// <remarks/>
        public string street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.geocoder.us/Geo/Coder/US/")]
    public partial class GeocoderIntersectionResult {
        
        private int zipField;
        
        private string suffix1Field;
        
        private string prefix1Field;
        
        private string type1Field;
        
        private string street1Field;
        
        private string suffix2Field;
        
        private string prefix2Field;
        
        private string type2Field;
        
        private string street2Field;
        
        private string stateField;
        
        private string cityField;
        
        private float latField;
        
        private float longField;
        
        /// <remarks/>
        public int zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string suffix1 {
            get {
                return this.suffix1Field;
            }
            set {
                this.suffix1Field = value;
            }
        }
        
        /// <remarks/>
        public string prefix1 {
            get {
                return this.prefix1Field;
            }
            set {
                this.prefix1Field = value;
            }
        }
        
        /// <remarks/>
        public string type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
            }
        }
        
        /// <remarks/>
        public string street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        public string suffix2 {
            get {
                return this.suffix2Field;
            }
            set {
                this.suffix2Field = value;
            }
        }
        
        /// <remarks/>
        public string prefix2 {
            get {
                return this.prefix2Field;
            }
            set {
                this.prefix2Field = value;
            }
        }
        
        /// <remarks/>
        public string type2 {
            get {
                return this.type2Field;
            }
            set {
                this.type2Field = value;
            }
        }
        
        /// <remarks/>
        public string street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public float lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public float @long {
            get {
                return this.longField;
            }
            set {
                this.longField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.geocoder.us/Geo/Coder/US/")]
    public partial class GeocoderAddressResult {
        
        private int numberField;
        
        private int zipField;
        
        private string suffixField;
        
        private string prefixField;
        
        private string typeField;
        
        private string streetField;
        
        private string stateField;
        
        private string cityField;
        
        private float latField;
        
        private float longField;
        
        /// <remarks/>
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public int zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public float lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        public float @long {
            get {
                return this.longField;
            }
            set {
                this.longField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void geocodeCompletedEventHandler(object sender, geocodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class geocodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal geocodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeocoderResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeocoderResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void geocode_addressCompletedEventHandler(object sender, geocode_addressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class geocode_addressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal geocode_addressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeocoderAddressResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeocoderAddressResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void geocode_intersectionCompletedEventHandler(object sender, geocode_intersectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class geocode_intersectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal geocode_intersectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeocoderIntersectionResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeocoderIntersectionResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591