using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
using System.ComponentModel;
using System.Xml.Serialization;

namespace TerraViewer
{
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class AstroObject
    {

        private string messierNameField;

        private string nGCNameField;

        private string popularName1Field;

        private double ra2000Field;

        private bool ra2000FieldSpecified;

        private double dec2000Field;

        private bool dec2000FieldSpecified;

        private float visualMagnitudeField;

        private bool visualMagnitudeFieldSpecified;

        private string constellationNameField;

        private string objectTypeField;

        /// <remarks/>
        public string MessierName
        {
            get
            {
                return messierNameField;
            }
            set
            {
                messierNameField = value;
            }
        }

        /// <remarks/>
        public string NGCName
        {
            get
            {
                return nGCNameField;
            }
            set
            {
                nGCNameField = value;
            }
        }

        /// <remarks/>
        public string PopularName1
        {
            get
            {
                return popularName1Field;
            }
            set
            {
                popularName1Field = value;
            }
        }

        /// <remarks/>
        public double Ra2000
        {
            get
            {
                return ra2000Field;
            }
            set
            {
                ra2000Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool Ra2000Specified
        {
            get
            {
                return ra2000FieldSpecified;
            }
            set
            {
                ra2000FieldSpecified = value;
            }
        }

        /// <remarks/>
        public double Dec2000
        {
            get
            {
                return dec2000Field;
            }
            set
            {
                dec2000Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool Dec2000Specified
        {
            get
            {
                return dec2000FieldSpecified;
            }
            set
            {
                dec2000FieldSpecified = value;
            }
        }

        /// <remarks/>
        public float VisualMagnitude
        {
            get
            {
                return visualMagnitudeField;
            }
            set
            {
                visualMagnitudeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool VisualMagnitudeSpecified
        {
            get
            {
                return visualMagnitudeFieldSpecified;
            }
            set
            {
                visualMagnitudeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ConstellationName
        {
            get
            {
                return constellationNameField;
            }
            set
            {
                constellationNameField = value;
            }
        }

        /// <remarks/>
        public string ObjectType
        {
            get
            {
                return objectTypeField;
            }
            set
            {
                objectTypeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class ImageSet
    {

        private string creditsField;

        private string creditsUrlField;

        private string thumbnailUrlField;

        private ImageSetGeneric genericField = ImageSetGeneric.False;

        private ImageSetType dataSetTypeField = ImageSetType.Sky;

        private BandPass bandPassField = BandPass.Visible;

        private string urlField;

        private int tileLevelsField;

        private double widthFactorField = 1;

        private ImageSetSparse sparseField = ImageSetSparse.False;

        private double rotationField;

        private string quadTreeMapField = "0123";

        private ProjectionType projectionField = ProjectionType.Tangent;

        private bool projectionFieldSpecified;

        private string nameField;

        private string fileTypeField;

        private double centerYField;

        private double centerXField;

        private ImageSetBottomsUp bottomsUpField = ImageSetBottomsUp.False;

        private ImageSetFlipX flipXField;

        private bool flipXFieldSpecified;

        private ImageSetFlipY flipYField;

        private bool flipYFieldSpecified;

        private ImageSetStockSet stockSetField;

        private bool stockSetFieldSpecified;

        private ImageSetElevationModel elevationModelField;

        private bool elevationModelFieldSpecified;

        private ImageSetStudy studyField;

        private bool studyFieldSpecified;

        private double offsetXField;

        private bool offsetXFieldSpecified;

        private double offsetYField;

        private bool offsetYFieldSpecified;

        private int baseTileLevelField;

        private double baseDegreesPerTileField;

        private string searchTagField;

        private string commentField;
        private string referenceFrame;

        private double meanRadiusField;

        bool meanRadiusFieldSpecified;

        [XmlIgnore]
        public bool MeanRadiusFieldSpecified
        {
            get { return meanRadiusField != 0; }
            set { meanRadiusFieldSpecified = value; }
        }
  
        long communityIdField;
        [XmlAttribute]
        public long MSRCommunityId
        {
            get { return communityIdField; }
            set { communityIdField = value; }
        }

        long componentIdField;
        [XmlAttribute]
        public long MSRComponentId
        {
            get { return componentIdField; }
            set { componentIdField = value; }
        }

        long permissionField;
        [XmlAttribute]
        public long Permission
        {
            get { return permissionField; }
            set { permissionField = value; }
        }


        /// <remarks/>
        public string Credits
        {
            get
            {
                return creditsField;
            }
            set
            {
                creditsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string CreditsUrl
        {
            get
            {
                return creditsUrlField;
            }
            set
            {
                creditsUrlField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "anyURI")]
        public string ThumbnailUrl
        {
            get
            {
                return thumbnailUrlField;
            }
            set
            {
                thumbnailUrlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetGeneric Generic
        {
            get
            {
                return genericField;
            }
            set
            {
                genericField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetType DataSetType
        {
            get
            {
                return dataSetTypeField;
            }
            set
            {
                dataSetTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public BandPass BandPass
        {
            get
            {
                return bandPassField;
            }
            set
            {
                bandPassField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string Url
        {
            get
            {
                return urlField;
            }
            set
            {
                urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public int TileLevels
        {
            get
            {
                return tileLevelsField;
            }
            set
            {
                tileLevelsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double WidthFactor
        {
            get
            {
                return widthFactorField;
            }
            set
            {
                widthFactorField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetSparse Sparse
        {
            get
            {
                return sparseField;
            }
            set
            {
                sparseField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Rotation
        {
            get
            {
                return rotationField;
            }
            set
            {
                matrixComputed = false;
                rotationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string QuadTreeMap
        {
            get
            {
                return quadTreeMapField;
            }
            set
            {
                quadTreeMapField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ProjectionType Projection
        {
            get
            {
                return projectionField;
            }
            set
            {
                projectionFieldSpecified = true;
                projectionField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool ProjectionSpecified
        {
            get
            {
                return projectionFieldSpecified;
            }
            set
            {
                projectionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get
            {
                return nameField;
            }
            set
            {
                nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string FileType
        {
            get
            {
                return fileTypeField;
            }
            set
            {
                fileTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double CenterY
        {
            get
            {
                return centerYField;
            }
            set
            {
                centerYField = value;
                matrixComputed = false;

            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double CenterX
        {
            get
            {
                return centerXField;
            }
            set
            {
                centerXField = value;
                matrixComputed = false;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetBottomsUp BottomsUp
        {
            get
            {
                return bottomsUpField;
            }
            set
            {
                bottomsUpField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetFlipX FlipX
        {
            get
            {
                return flipXField;
            }
            set
            {
                flipXField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool FlipXSpecified
        {
            get
            {
                return flipXFieldSpecified;
            }
            set
            {
                flipXFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetFlipY FlipY
        {
            get
            {
                return flipYField;
            }
            set
            {
                flipYField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool FlipYSpecified
        {
            get
            {
                return flipYFieldSpecified;
            }
            set
            {
                flipYFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetStockSet StockSet
        {
            get
            {
                return stockSetField;
            }
            set
            {
                stockSetField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool StockSetSpecified
        {
            get
            {
                return stockSetFieldSpecified;
            }
            set
            {
                stockSetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetElevationModel ElevationModel
        {
            get
            {
                return elevationModelField;
            }
            set
            {
                elevationModelField = value;
                elevationModelFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool ElevationModelSpecified
        {
            get
            {
                return elevationModelFieldSpecified;
            }
            set
            {
                elevationModelFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetStudy Study
        {
            get
            {
                return studyField;
            }
            set
            {
                studyField = value;
                studyFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool StudySpecified
        {
            get
            {
                return studyFieldSpecified;
            }
            set
            {
                studyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double OffsetX
        {
            get
            {
                return offsetXField;
            }
            set
            {
                offsetXFieldSpecified = true;
                offsetXField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool OffsetXSpecified
        {
            get
            {
                return offsetXFieldSpecified;
            }
            set
            {
                offsetXFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double OffsetY
        {
            get
            {
                return offsetYField;
            }
            set
            {
                offsetYFieldSpecified = true;

                offsetYField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool OffsetYSpecified
        {
            get
            {
                return offsetYFieldSpecified;
            }
            set
            {
                offsetYFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public int BaseTileLevel
        {
            get
            {
                return baseTileLevelField;
            }
            set
            {
                baseTileLevelField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double BaseDegreesPerTile
        {
            get
            {
                return baseDegreesPerTileField;
            }
            set
            {
                baseDegreesPerTileField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SearchTag
        {
            get
            {
                return searchTagField;
            }
            set
            {
                searchTagField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Comment
        {
            get
            {
                return commentField;
            }
            set
            {
                commentField = value;
            }
        } 
        
        /// <remarks/>
        [XmlAttribute]
        public string ReferenceFrame
        {
            get
            {
                return referenceFrame;
            }
            set
            {
                referenceFrame = value;
            }
        }   

        /// <remarks/>
        [XmlAttribute]
        public double MeanRadius
        {
            get
            {
                return meanRadiusField;
            }
            set
            {

                meanRadiusFieldSpecified = (value != 0);


                meanRadiusField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetGeneric
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }

    

    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public enum ImageSetBandPass
    //{

    //    /// <remarks/>
    //    Gamma,

    //    /// <remarks/>
    //    XRay,

    //    /// <remarks/>
    //    Ultraviolet,

    //    /// <remarks/>
    //    Visible,

    //    /// <remarks/>
    //    HydrogenAlpha,

    //    /// <remarks/>
    //    IR,

    //    /// <remarks/>
    //    Microwave,

    //    /// <remarks/>
    //    Radio,

    //    /// <remarks/>
    //    VisibleNight,
    //}

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetSparse
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public enum ImageSetProjection
    //{

    //    /// <remarks/>
    //    Mercator,

    //    /// <remarks/>
    //    Equirectangular,

    //    /// <remarks/>
    //    Tangent,
    //    Tan = Tangent,

    //    /// <remarks/>
    //    Toast,

    //    /// <remarks/>
    //    Spherical,
    //}

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetBottomsUp
    {

        /// <remarks/>
        False,

        /// <remarks/>
        True,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetFlipX
    {

        /// <remarks/>
        False,

        /// <remarks/>
        True,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetFlipY
    {

        /// <remarks/>
        False,

        /// <remarks/>
        True,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetStockSet
    {

        /// <remarks/>
        False,

        /// <remarks/>
        True,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetElevationModel
    {

        /// <remarks/>
        False,

        /// <remarks/>
        True,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ImageSetStudy
    {

        /// <remarks/>
        False,

        /// <remarks/>
        True,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class Place
    {

        private object descriptionField;

        private PlaceBackgroundImageSet backgroundImageSetField;

        private PlaceForegroundImageSet foregroundImageSetField;

        private ImageSet imageSetField;

        private string nameField;

        private ImageSetType dataSetTypeField = ImageSetType.Sky;

        private double raField;

        private bool raFieldSpecified;

        private double decField;

        private bool decFieldSpecified;

        private double latField;

        private bool latFieldSpecified;

        private double lngField;

        private bool lngFieldSpecified;

        private string constellationField;

        private Classification classificationField = Classification.Unidentified;

        private bool classificationFieldSpecified;

        private double magnitudeField;

        private double distanceField;

        private double zoomLevelField;

        private double rotationField;

        private double angleField;

        private double domeAltField;

        private double domeAzField;

        private double opacityField;

        private double anglularSizeField;

        private bool anglularSizeFieldSpecified;

        private string thumbnailField;

        long communityIdField;
        [XmlAttribute]
        public long MSRCommunityId
        {
            get { return communityIdField; }
            set { communityIdField = value; }
        }
        long componentIdField;
        [XmlAttribute]
        public long MSRComponentId
        {
            get { return componentIdField; }
            set { componentIdField = value; }
        }

        long permissionField;
        [XmlAttribute]
        public long Permission
        {
            get { return permissionField; }
            set { permissionField = value; }
        }

        /// <remarks/>
        public object Description
        {
            get
            {
                return descriptionField;
            }
            set
            {
                descriptionField = value;
            }
        }

        /// <remarks/>
        public PlaceBackgroundImageSet BackgroundImageSet
        {
            get
            {
                return backgroundImageSetField;
            }
            set
            {
                backgroundImageSetField = value;
            }
        }

        /// <remarks/>
        public PlaceForegroundImageSet ForegroundImageSet
        {
            get
            {
                return foregroundImageSetField;
            }
            set
            {
                foregroundImageSetField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string Thumbnail
        {
            get
            {
                return thumbnailField;
            }
            set
            {
                thumbnailField = value;
            }
        }

        /// <remarks/>
        public ImageSet ImageSet
        {
            get
            {
                return imageSetField;
            }
            set
            {
                imageSetField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get
            {
                return Names[0];
            }
            set
            {
                nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public ImageSetType DataSetType
        {
            get
            {
                return dataSetTypeField;
            }
            set
            {
                dataSetTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double RA
        {
            get
            {

                return raField;
            }
            set
            {
                raField = value;
                raFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool RASpecified
        {
            get
            {
                return raFieldSpecified;
            }
            set
            {
                raFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Dec
        {
            get
            {
                return decField;
            }
            set
            {
                decField = value;
                decFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool DecSpecified
        {
            get
            {
                return decFieldSpecified;
            }
            set
            {
                decFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Lat
        {
            get
            {
                return latField;
            }
            set
            {
                latField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool LatSpecified
        {
            get
            {
                return latFieldSpecified;
            }
            set
            {
                latFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Lng
        {
            get
            {
                return lngField;
            }
            set
            {
                lngField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool LngSpecified
        {
            get
            {
                return lngFieldSpecified;
            }
            set
            {
                lngFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Constellation
        {
            get
            {
                return constellationField;
            }
            set
            {
                constellationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public Classification Classification
        {
            get
            {
                return classificationField;
            }
            set
            {
                classificationField = value;
                classificationFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool ClassificationSpecified
        {
            get
            {
                return classificationFieldSpecified;
            }
            set
            {
                classificationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Magnitude
        {
            get
            {
                return magnitudeField;
            }
            set
            {
                magnitudeField = value;
            }
        }
        /// <remarks/>
        [XmlAttribute]
        public double Distance
        {
            get
            {
                return distanceField;
            }
            set
            {
                distanceField = value;
            }
        }
        /// <remarks/>
        [XmlAttribute]
        public double ZoomLevel
        {
            get
            {
                return zoomLevelField;
            }
            set
            {
                zoomLevelField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Rotation
        {
            get
            {
                return rotationField;
            }
            set
            {
                rotationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Angle
        {
            get
            {
                return angleField;
            }
            set
            {
                angleField = value;
            }
        }

        [XmlAttribute]
        public double DomeAlt
        {
            get
            {
                return domeAltField;
            }
            set
            {
                domeAltField = value;
            }
        }
        [XmlAttribute]
        public double DomeAz
        {
            get
            {
                return domeAzField;
            }
            set
            {
                domeAzField = value;
            }
        }     
        
        /// <remarks/>
        [XmlAttribute]
        public double Opacity
        {
            get
            {
                return opacityField;
            }
            set
            {
                opacityField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double AngularSize
        {
            get
            {
                return anglularSizeField;
            }
            set
            {
                anglularSizeField = value;
                anglularSizeFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool AnglularSizeSpecified
        {
            get
            {
                return anglularSizeFieldSpecified;
            }
            set
            {
                anglularSizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class PlaceBackgroundImageSet
    {

        private ImageSet imageSetField;

        /// <remarks/>
        public ImageSet ImageSet
        {
            get
            {
                return imageSetField;
            }
            set
            {
                imageSetField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    //System.Diagnostics.DebuggerStepThroughAttribute()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class PlaceForegroundImageSet
    {

        private ImageSet imageSetField;

        /// <remarks/>
        public ImageSet ImageSet
        {
            get
            {
                return imageSetField;
            }
            set
            {
                imageSetField = value;
            }
        }
    }



    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //public enum Classification
    //{
    //    Star = 1,
    //    Supernova = 2,
    //    BlackHole = 4,
    //    NeutronStar = 8,
    //    DoubleStar = 16,
    //    MultipleStars = 32,
    //    Asterism = 64,
    //    Constellation = 128,
    //    OpenCluster = 256,
    //    GlobularCluster = 512,
    //    NebulousCluster = 1024,
    //    Nebula = 2048,
    //    EmissionNebula = 4096,
    //    PlanetaryNebula = 8192,
    //    ReflectionNebula = 16384,
    //    DarkNebula = 32768,
    //    GiantMolecularCloud = 65536,
    //    SupernovaRemnant = 131072,
    //    InterstellarDust = 262144,
    //    Quasar = 524288,
    //    Galaxy = 1048576,
    //    SpiralGalaxy = 2097152,
    //    IrregularGalaxy = 4194304,
    //    EllipticalGalaxy = 8388608,
    //    Knot = 16777216,
    //    PlateDefect = 33554432,
    //    ClusterOfGalaxies = 67108864,
    //    OtherNGC = 134217728,
    //    Unidentified = 268435456,
    //    SolarSystem = 536870912,
    //    Unfiltered = 1073741823,
    //    Stellar = 63,
    //    StellarGroupings = 2032,
    //    Nebulae = 523264,
    //    Galactic = 133693440,
    //    Other = 436207616
    //};

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    //System.Diagnostics.DebuggerStepThroughAttribute()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class LinePoint
    {

        private string nameField;

        private double raField;

        private bool raFieldSpecified;

        private double decField;

        private bool decFieldSpecified;

        private string widthField;

        private string colorField;

        private LinePointPointType pointTypeField;

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get
            {
                return nameField;
            }
            set
            {
                nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double RA
        {
            get
            {
                return raField;
            }
            set
            {
                raField = value;
                raFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool RASpecified
        {
            get
            {
                return raFieldSpecified;
            }
            set
            {
                raFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double Dec
        {
            get
            {
                return decField;
            }
            set
            {
                decField = value;
                decFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool DecSpecified
        {
            get
            {
                return decFieldSpecified;
            }
            set
            {
                decFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string Width
        {
            get
            {
                return widthField;
            }
            set
            {
                widthField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Color
        {
            get
            {
                return colorField;
            }
            set
            {
                colorField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public LinePointPointType PointType
        {
            get
            {
                return pointTypeField;
            }
            set
            {
                pointTypeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum LinePointPointType
    {

        /// <remarks/>
        Move,

        /// <remarks/>
        Line,

        /// <remarks/>
        Dash,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    //System.Diagnostics.DebuggerStepThroughAttribute()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class LineSet
    {

        private LinePoint[] linePointField;

        private string nameField;

        /// <remarks/>
        [XmlElement("LinePoint")]
        public LinePoint[] LinePoint
        {
            get
            {
                return linePointField;
            }
            set
            {
                linePointField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get
            {
                return nameField;
            }
            set
            {
                nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class Tour
    {

        private TourUserLevel userLevelField;

        private string titleField;

        private string taxonomyField;

        private string organizationNameField;

        private string organizationUrlField;

        private string idField;

        private string descriptionField;

        private TourClassification classificationField;

        private string authorEmailField;

        private string authorField;

        private string tourDurationField;

        private string authorURLField;

        private double averageRatingField;

        private double lengthInSecsField;

        private string tourAttributionAndCreditsField;

        private string tourUrlField;

 
        private string authorImageUrlField;


        private string thumbnailUrlField;

        private string keywordsField;

        private string relatedToursField;

        long communityIdField;
        [XmlAttribute]
        public long MSRCommunityId
        {
            get { return communityIdField; }
            set { communityIdField = value; }
        }

        long componentIdField;
        [XmlAttribute]
        public long MSRComponentId
        {
            get { return componentIdField; }
            set { componentIdField = value; }
        }

        long permissionField;
        [XmlAttribute]
        public long Permission
        {
            get { return permissionField; }
            set { permissionField = value; }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string TourUrl
        {
            get
            {
                if (string.IsNullOrEmpty(tourUrlField))
                {
                    return string.Format("http://cdn.worldwidetelescope.org/wwtweb/GetTour.aspx?GUID={0}", Id);
                }
                return tourUrlField;
            }
            set { tourUrlField = value; }
        }

        [XmlAttribute(DataType = "anyURI")]
        public string AuthorImageUrl
        {
            get { return authorImageUrlField; }
            set { authorImageUrlField = value; }
        }   

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string ThumbnailUrl
        {
            get { return thumbnailUrlField; }
            set { thumbnailUrlField = value; }
        }

        [XmlAttribute]
        public TourUserLevel UserLevel
        {
            get
            {
                return userLevelField;
            }
            set
            {
                userLevelField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Title
        {
            get
            {
                return titleField;
            }
            set
            {
                titleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Taxonomy
        {
            get
            {
                return taxonomyField;
            }
            set
            {
                taxonomyField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string OrganizationName
        {
            get
            {
                return organizationNameField;
            }
            set
            {
                organizationNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string OrganizationUrl
        {
            get
            {
                return organizationUrlField;
            }
            set
            {
                organizationUrlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string ID
        {
            get
            {
                return idField;
            }
            set
            {
                idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Description
        {
            get
            {
                return descriptionField;
            }
            set
            {
                descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public TourClassification Classification
        {
            get
            {
                return classificationField;
            }
            set
            {
                classificationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string AuthorEmail
        {
            get
            {
                return authorEmailField;
            }
            set
            {
                authorEmailField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Author
        {
            get
            {
                return authorField;
            }
            set
            {
                authorField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "duration")]
        public string TourDuration
        {
            get
            {
                return tourDurationField;
            }
            set
            {
                tourDurationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string AuthorURL
        {
            get
            {
                return authorURLField;
            }
            set
            {
                authorURLField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double AverageRating
        {
            get
            {
                return averageRatingField;
            }
            set
            {
                averageRatingField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public double LengthInSecs
        {
            get
            {
                return lengthInSecsField;
            }
            set
            {
                lengthInSecsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string TourAttributionAndCredits
        {
            get
            {
                return tourAttributionAndCreditsField;
            }
            set
            {
                tourAttributionAndCreditsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string RelatedTours
        {
            get
            {
                return relatedToursField;
            }
            set
            {
                relatedToursField = value;
            }
        }
        /// <remarks/>
        [XmlAttribute]
        public string Keywords
        {
            get
            {
                return keywordsField;
            }
            set
            {
                keywordsField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum TourUserLevel
    {

        /// <remarks/>
        Beginner,

        /// <remarks/>
        Intermediate,

        /// <remarks/>
        Advanced,

        /// <remarks/>
        Educator,

        /// <remarks/>
        Professional,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum TourClassification
    {

        /// <remarks/>
        Star,

        /// <remarks/>
        Supernova,

        /// <remarks/>
        BlackHole,

        /// <remarks/>
        NeutronStar,

        /// <remarks/>
        DoubleStar,

        /// <remarks/>
        MultipleStars,

        /// <remarks/>
        Asterism,

        /// <remarks/>
        Constellation,

        /// <remarks/>
        OpenCluster,

        /// <remarks/>
        GlobularCluster,

        /// <remarks/>
        NebulousCluster,

        /// <remarks/>
        Nebula,

        /// <remarks/>
        EmissionNebula,

        /// <remarks/>
        PlanetaryNebula,

        /// <remarks/>
        ReflectionNebula,

        /// <remarks/>
        DarkNebula,

        /// <remarks/>
        GiantMolecularCloud,

        /// <remarks/>
        SupernovaRemnant,

        /// <remarks/>
        InterstellarDust,

        /// <remarks/>
        Quasar,

        /// <remarks/>
        Galaxy,

        /// <remarks/>
        SpiralGalaxy,

        /// <remarks/>
        IrregularGalaxy,

        /// <remarks/>
        EllipticalGalaxy,

        /// <remarks/>
        Knot,

        /// <remarks/>
        PlateDefect,

        /// <remarks/>
        ClusterOfGalaxies,

        /// <remarks/>
        OtherNGC,

        /// <remarks/>
        Unidentified,

        /// <remarks/>
        Unfiltered,

        /// <remarks/>
        Stellar,

        /// <remarks/>
        StellarGroupings,

        /// <remarks/>
        Nebulae,

        /// <remarks/>
        Galactic,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class Folder
    {


        private Place[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private ImageSet[] imageSetField;

        private LineSet[] lineSetField;

        private Tour[] tourField;

        private string nameField;

        private FolderGroup groupField;

        private string urlField;

        private string thumbnailField;

        private FolderRefreshType refreshTypeField;

        private bool refreshTypeFieldSpecified;

        private string refreshIntervalField;

        private FolderBrowseable browseableField = FolderBrowseable.True;

        private bool browseableFieldSpecified;

        private FolderSearchable searchableField = FolderSearchable.False;

        private FolderType typeField;

        private string subTypeField;

        private List<Folder> folders = new List<Folder>();
        private List<Place> places = new List<Place>();
        private List<ImageSet> imagesets = new List<ImageSet>();
        /// <remarks/>
        /// 

        long communityIdField;
        [XmlAttribute]
        public long MSRCommunityId
        {
            get { return communityIdField; }
            set { communityIdField = value; }
        }

        long componentIdField;
        [XmlAttribute]
        public long MSRComponentId
        {
            get { return componentIdField; }
            set { componentIdField = value; }
        }

        long permissionField;
        [XmlAttribute]
        public long Permission
        {
            get { return permissionField; }
            set { permissionField = value; }
        }

        [XmlElement("Folder")]
        public Folder[] Folder1
        {
            get
            {
                return folders.ToArray();
            }
            set
            {
                folders.Clear();
                if (value != null)
                {
                    folders.AddRange(value);
                }
            }
        }

        /// <remarks/>
        [XmlElement("Place", typeof(Place))]
        public Place[] Items
        {
            get
            {
                return places.ToArray();
            }
            set
            {
                places.Clear();
                if (value != null)
                {
                    places.AddRange(value);
                }
            }
        }

        /// <remarks/>
      //  [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return itemsElementNameField;
            }
            set
            {
                itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ImageSet", typeof(ImageSet))]
        public ImageSet[] ImageSet
        {
             get
            {
                return imagesets.ToArray();
            }
            set
            {
                imagesets.Clear();
                if (value != null)
                {
                    imagesets.AddRange(value);
                }
            }
            //get
            //{
            //    return this.imageSetField;
            //}
            //set
            //{
            //    this.imageSetField = value;
            //}
        }

        /// <remarks/>
        [XmlElement("LineSet")]
        public LineSet[] LineSet
        {
            get
            {
                return lineSetField;
            }
            set
            {
                lineSetField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Tour")]
        public Tour[] Tour
        {
            get
            {
                return tourField;
            }
            set
            {
                tourField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string Name
        {
            get
            {
                if (nameField == null)
                {
                    return "";
                }
                return nameField;
            }
            set
            {
                nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public FolderGroup Group
        {
            get
            {
                return groupField;
            }
            set
            {
                groupField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string Url
        {
            get
            {
                return urlField;
            }
            set
            {
                urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "anyURI")]
        public string Thumbnail
        {
            get
            {
                return thumbnailField;
            }
            set
            {
                thumbnailField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public FolderRefreshType RefreshType
        {
            get
            {
                return refreshTypeField;
            }
            set
            {
                refreshTypeField = value;
                RefreshTypeSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool RefreshTypeSpecified
        {
            get
            {
                return refreshTypeFieldSpecified;
            }
            set
            {
                refreshTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "duration")]
        public string RefreshInterval
        {
            get
            {
                return refreshIntervalField;
            }
            set
            {
                refreshIntervalField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public FolderBrowseable Browseable
        {
            get
            {
                return browseableField;
            }
            set
            {
                browseableField = value;
                browseableFieldSpecified = true;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool BrowseableSpecified
        {
            get
            {
                return browseableFieldSpecified;
            }
            set
            {
                browseableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public FolderSearchable Searchable
        {
            get
            {
                return searchableField;
            }
            set
            {
                searchableField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public FolderType Type
        {
            get
            {
                return typeField;
            }
            set
            {
                typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public string SubType
        {
            get
            {
                return subTypeField;
            }
            set
            {
                subTypeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        EndTarget,

        /// <remarks/>
        Place,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum FolderGroup
    {

        /// <remarks/>
        Explorer,

        /// <remarks/>
        Tour,

        /// <remarks/>
        Search,

        /// <remarks/>
        Constellation,

        /// <remarks/>
        View,

        /// <remarks/>
        Goto,

        /// <remarks/>
        Community,

        /// <remarks/>
        Context,

        /// <remarks/>
        VoTable,

        /// <remarks/>
        ImageStack
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum FolderRefreshType
    {

        /// <remarks/>
        Interval,

        /// <remarks/>
        ConditionalGet,

        /// <remarks/>
        ViewChange,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum FolderBrowseable
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum FolderSearchable
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum FolderType
    {

        /// <remarks/>
        Earth,

        /// <remarks/>
        Planet,

        /// <remarks/>
        Sky,

        /// <remarks/>
        Panorama,
    }
}
