//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.IO;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OnlineResource {
    
    private string typeField;
    
    private string hrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class LatLonBoundingBox {
    
    private string minxField;
    
    private string minyField;
    
    private string maxxField;
    
    private string maxyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minx {
        get {
            return this.minxField;
        }
        set {
            this.minxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string miny {
        get {
            return this.minyField;
        }
        set {
            this.minyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxx {
        get {
            return this.maxxField;
        }
        set {
            this.maxxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxy {
        get {
            return this.maxyField;
        }
        set {
            this.maxyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class WMS_Tile_Service {
    
    private WMS_Tile_ServiceService[] serviceField;
    
    private WMS_Tile_ServiceTiledPatterns[] tiledPatternsField;
    
    private string versionField;

    public static WMS_Tile_Service LoadFromSream(Stream stream)
    {
        XmlSerializer serializer = new XmlSerializer(typeof(WMS_Tile_Service));
        WMS_Tile_Service newCaps = (WMS_Tile_Service)serializer.Deserialize(stream);

        return newCaps;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Service", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceService[] Service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TiledPatterns", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceTiledPatterns[] TiledPatterns {
        get {
            return this.tiledPatternsField;
        }
        set {
            this.tiledPatternsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceService {
    
    private string nameField;
    
    private string titleField;
    
    private string abstractField;
    
    private string feesField;
    
    private string accessConstraintsField;
    
    private WMS_Tile_ServiceServiceKeywordListKeyword[] keywordListField;
    
    private OnlineResource[] onlineResourceField;
    
    private WMS_Tile_ServiceServiceContactInformation[] contactInformationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Fees {
        get {
            return this.feesField;
        }
        set {
            this.feesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AccessConstraints {
        get {
            return this.accessConstraintsField;
        }
        set {
            this.accessConstraintsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Keyword", typeof(WMS_Tile_ServiceServiceKeywordListKeyword), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceServiceKeywordListKeyword[] KeywordList {
        get {
            return this.keywordListField;
        }
        set {
            this.keywordListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OnlineResource")]
    public OnlineResource[] OnlineResource {
        get {
            return this.onlineResourceField;
        }
        set {
            this.onlineResourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceServiceContactInformation[] ContactInformation {
        get {
            return this.contactInformationField;
        }
        set {
            this.contactInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceServiceKeywordListKeyword {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceServiceContactInformation {
    
    private string contactElectronicMailAddressField;
    
    private WMS_Tile_ServiceServiceContactInformationContactPersonPrimary[] contactPersonPrimaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContactElectronicMailAddress {
        get {
            return this.contactElectronicMailAddressField;
        }
        set {
            this.contactElectronicMailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactPersonPrimary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceServiceContactInformationContactPersonPrimary[] ContactPersonPrimary {
        get {
            return this.contactPersonPrimaryField;
        }
        set {
            this.contactPersonPrimaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceServiceContactInformationContactPersonPrimary {
    
    private string contactPersonField;
    
    private string contactOrganizationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContactPerson {
        get {
            return this.contactPersonField;
        }
        set {
            this.contactPersonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContactOrganization {
        get {
            return this.contactOrganizationField;
        }
        set {
            this.contactOrganizationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceTiledPatterns {
    
    private OnlineResource[] onlineResourceField;
    
    private LatLonBoundingBox[] latLonBoundingBoxField;
    
    private WMS_Tile_ServiceTiledPatternsTiledGroup[] tiledGroupField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OnlineResource")]
    public OnlineResource[] OnlineResource {
        get {
            return this.onlineResourceField;
        }
        set {
            this.onlineResourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LatLonBoundingBox")]
    public LatLonBoundingBox[] LatLonBoundingBox {
        get {
            return this.latLonBoundingBoxField;
        }
        set {
            this.latLonBoundingBoxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TiledGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceTiledPatternsTiledGroup[] TiledGroup {
        get {
            return this.tiledGroupField;
        }
        set {
            this.tiledGroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceTiledPatternsTiledGroup {
    
    private string nameField;
    
    private string titleField;
    
    private string abstractField;
    
    private string projectionField;
    
    private string padField;
    
    private string bandsField;
    
    private WMS_Tile_ServiceTiledPatternsTiledGroupDataValues[] dataValuesField;
    
    private LatLonBoundingBox[] latLonBoundingBoxField;
    
    private WMS_Tile_ServiceTiledPatternsTiledGroupBoundingBox[] boundingBoxField;
    
    private WMS_Tile_ServiceTiledPatternsTiledGroupTilePattern[] tilePatternField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Projection {
        get {
            return this.projectionField;
        }
        set {
            this.projectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Pad {
        get {
            return this.padField;
        }
        set {
            this.padField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bands {
        get {
            return this.bandsField;
        }
        set {
            this.bandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceTiledPatternsTiledGroupDataValues[] DataValues {
        get {
            return this.dataValuesField;
        }
        set {
            this.dataValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LatLonBoundingBox")]
    public LatLonBoundingBox[] LatLonBoundingBox {
        get {
            return this.latLonBoundingBoxField;
        }
        set {
            this.latLonBoundingBoxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BoundingBox", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public WMS_Tile_ServiceTiledPatternsTiledGroupBoundingBox[] BoundingBox {
        get {
            return this.boundingBoxField;
        }
        set {
            this.boundingBoxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TilePattern", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public WMS_Tile_ServiceTiledPatternsTiledGroupTilePattern[] TilePattern {
        get {
            return this.tilePatternField;
        }
        set {
            this.tilePatternField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceTiledPatternsTiledGroupDataValues {
    
    private string minField;
    
    private string maxField;
    
    private string noDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NoData {
        get {
            return this.noDataField;
        }
        set {
            this.noDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceTiledPatternsTiledGroupBoundingBox {
    
    private string minxField;
    
    private string minyField;
    
    private string maxxField;
    
    private string maxyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minx {
        get {
            return this.minxField;
        }
        set {
            this.minxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string miny {
        get {
            return this.minyField;
        }
        set {
            this.minyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxx {
        get {
            return this.maxxField;
        }
        set {
            this.maxxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxy {
        get {
            return this.maxyField;
        }
        set {
            this.maxyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class WMS_Tile_ServiceTiledPatternsTiledGroupTilePattern {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LatLonBoundingBox", typeof(LatLonBoundingBox))]
    [System.Xml.Serialization.XmlElementAttribute("OnlineResource", typeof(OnlineResource))]
    [System.Xml.Serialization.XmlElementAttribute("WMS_Tile_Service", typeof(WMS_Tile_Service))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
