//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TerraViewer.org.worldwidetelescope.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WWTWebServiceSoap", Namespace="http://research.microsoft.com/WWT/")]
    public partial class WWTWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAstroObjectsByRaDecOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAstroObjectsByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAstroObjectsInCatalogOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportTourOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTourWorkFlowStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetToursForGUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetToursForAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetToursForKeywordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetToursForDateRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WWTWebService() {
            this.Url = global::TerraViewer.Properties.Settings.Default.WWTExplorer_org_worldwidetelescope_www_WWTWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAstroObjectsByRaDecCompletedEventHandler GetAstroObjectsByRaDecCompleted;
        
        /// <remarks/>
        public event GetAstroObjectsByNameCompletedEventHandler GetAstroObjectsByNameCompleted;
        
        /// <remarks/>
        public event GetAstroObjectsInCatalogCompletedEventHandler GetAstroObjectsInCatalogCompleted;
        
        /// <remarks/>
        public event ImportTourCompletedEventHandler ImportTourCompleted;
        
        /// <remarks/>
        public event UpdateTourWorkFlowStatusCompletedEventHandler UpdateTourWorkFlowStatusCompleted;
        
        /// <remarks/>
        public event GetToursForGUIDCompletedEventHandler GetToursForGUIDCompleted;
        
        /// <remarks/>
        public event GetToursForAuthorCompletedEventHandler GetToursForAuthorCompleted;
        
        /// <remarks/>
        public event GetToursForKeywordCompletedEventHandler GetToursForKeywordCompleted;
        
        /// <remarks/>
        public event GetToursForDateRangeCompletedEventHandler GetToursForDateRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetAstroObjectsByRaDec", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AstroObjectsDataset GetAstroObjectsByRaDec(float Ra, float Dec, float PlusMinusArcSecs) {
            object[] results = this.Invoke("GetAstroObjectsByRaDec", new object[] {
                        Ra,
                        Dec,
                        PlusMinusArcSecs});
            return ((AstroObjectsDataset)(results[0]));
        }
        
        /// <remarks/>
        public void GetAstroObjectsByRaDecAsync(float Ra, float Dec, float PlusMinusArcSecs) {
            this.GetAstroObjectsByRaDecAsync(Ra, Dec, PlusMinusArcSecs, null);
        }
        
        /// <remarks/>
        public void GetAstroObjectsByRaDecAsync(float Ra, float Dec, float PlusMinusArcSecs, object userState) {
            if ((this.GetAstroObjectsByRaDecOperationCompleted == null)) {
                this.GetAstroObjectsByRaDecOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAstroObjectsByRaDecOperationCompleted);
            }
            this.InvokeAsync("GetAstroObjectsByRaDec", new object[] {
                        Ra,
                        Dec,
                        PlusMinusArcSecs}, this.GetAstroObjectsByRaDecOperationCompleted, userState);
        }
        
        private void OnGetAstroObjectsByRaDecOperationCompleted(object arg) {
            if ((this.GetAstroObjectsByRaDecCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAstroObjectsByRaDecCompleted(this, new GetAstroObjectsByRaDecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetAstroObjectsByName", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AstroObjectsDataset GetAstroObjectsByName(string AstroObjectName) {
            object[] results = this.Invoke("GetAstroObjectsByName", new object[] {
                        AstroObjectName});
            return ((AstroObjectsDataset)(results[0]));
        }
        
        /// <remarks/>
        public void GetAstroObjectsByNameAsync(string AstroObjectName) {
            this.GetAstroObjectsByNameAsync(AstroObjectName, null);
        }
        
        /// <remarks/>
        public void GetAstroObjectsByNameAsync(string AstroObjectName, object userState) {
            if ((this.GetAstroObjectsByNameOperationCompleted == null)) {
                this.GetAstroObjectsByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAstroObjectsByNameOperationCompleted);
            }
            this.InvokeAsync("GetAstroObjectsByName", new object[] {
                        AstroObjectName}, this.GetAstroObjectsByNameOperationCompleted, userState);
        }
        
        private void OnGetAstroObjectsByNameOperationCompleted(object arg) {
            if ((this.GetAstroObjectsByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAstroObjectsByNameCompleted(this, new GetAstroObjectsByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetAstroObjectsInCatalog", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AstroObjectsDataset GetAstroObjectsInCatalog(string CatalogName) {
            object[] results = this.Invoke("GetAstroObjectsInCatalog", new object[] {
                        CatalogName});
            return ((AstroObjectsDataset)(results[0]));
        }
        
        /// <remarks/>
        public void GetAstroObjectsInCatalogAsync(string CatalogName) {
            this.GetAstroObjectsInCatalogAsync(CatalogName, null);
        }
        
        /// <remarks/>
        public void GetAstroObjectsInCatalogAsync(string CatalogName, object userState) {
            if ((this.GetAstroObjectsInCatalogOperationCompleted == null)) {
                this.GetAstroObjectsInCatalogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAstroObjectsInCatalogOperationCompleted);
            }
            this.InvokeAsync("GetAstroObjectsInCatalog", new object[] {
                        CatalogName}, this.GetAstroObjectsInCatalogOperationCompleted, userState);
        }
        
        private void OnGetAstroObjectsInCatalogOperationCompleted(object arg) {
            if ((this.GetAstroObjectsInCatalogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAstroObjectsInCatalogCompleted(this, new GetAstroObjectsInCatalogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/ImportTour", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour[] ImportTour(string TourXML, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] TourBlob, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] TourThumbnail, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] AuthorThumbnail) {
            object[] results = this.Invoke("ImportTour", new object[] {
                        TourXML,
                        TourBlob,
                        TourThumbnail,
                        AuthorThumbnail});
            return ((Tour[])(results[0]));
        }
        
        /// <remarks/>
        public void ImportTourAsync(string TourXML, byte[] TourBlob, byte[] TourThumbnail, byte[] AuthorThumbnail) {
            this.ImportTourAsync(TourXML, TourBlob, TourThumbnail, AuthorThumbnail, null);
        }
        
        /// <remarks/>
        public void ImportTourAsync(string TourXML, byte[] TourBlob, byte[] TourThumbnail, byte[] AuthorThumbnail, object userState) {
            if ((this.ImportTourOperationCompleted == null)) {
                this.ImportTourOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportTourOperationCompleted);
            }
            this.InvokeAsync("ImportTour", new object[] {
                        TourXML,
                        TourBlob,
                        TourThumbnail,
                        AuthorThumbnail}, this.ImportTourOperationCompleted, userState);
        }
        
        private void OnImportTourOperationCompleted(object arg) {
            if ((this.ImportTourCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportTourCompleted(this, new ImportTourCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/UpdateTourWorkFlowStatus", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour[] UpdateTourWorkFlowStatus(string TourGUID, char WorkFlowStatusCode, string ApprovedRejectedByName) {
            object[] results = this.Invoke("UpdateTourWorkFlowStatus", new object[] {
                        TourGUID,
                        WorkFlowStatusCode,
                        ApprovedRejectedByName});
            return ((Tour[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTourWorkFlowStatusAsync(string TourGUID, char WorkFlowStatusCode, string ApprovedRejectedByName) {
            this.UpdateTourWorkFlowStatusAsync(TourGUID, WorkFlowStatusCode, ApprovedRejectedByName, null);
        }
        
        /// <remarks/>
        public void UpdateTourWorkFlowStatusAsync(string TourGUID, char WorkFlowStatusCode, string ApprovedRejectedByName, object userState) {
            if ((this.UpdateTourWorkFlowStatusOperationCompleted == null)) {
                this.UpdateTourWorkFlowStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTourWorkFlowStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateTourWorkFlowStatus", new object[] {
                        TourGUID,
                        WorkFlowStatusCode,
                        ApprovedRejectedByName}, this.UpdateTourWorkFlowStatusOperationCompleted, userState);
        }
        
        private void OnUpdateTourWorkFlowStatusOperationCompleted(object arg) {
            if ((this.UpdateTourWorkFlowStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTourWorkFlowStatusCompleted(this, new UpdateTourWorkFlowStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetToursForGUID", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour[] GetToursForGUID(string TourGUID) {
            object[] results = this.Invoke("GetToursForGUID", new object[] {
                        TourGUID});
            return ((Tour[])(results[0]));
        }
        
        /// <remarks/>
        public void GetToursForGUIDAsync(string TourGUID) {
            this.GetToursForGUIDAsync(TourGUID, null);
        }
        
        /// <remarks/>
        public void GetToursForGUIDAsync(string TourGUID, object userState) {
            if ((this.GetToursForGUIDOperationCompleted == null)) {
                this.GetToursForGUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetToursForGUIDOperationCompleted);
            }
            this.InvokeAsync("GetToursForGUID", new object[] {
                        TourGUID}, this.GetToursForGUIDOperationCompleted, userState);
        }
        
        private void OnGetToursForGUIDOperationCompleted(object arg) {
            if ((this.GetToursForGUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetToursForGUIDCompleted(this, new GetToursForGUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetToursForAuthor", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour[] GetToursForAuthor(string AuthorName) {
            object[] results = this.Invoke("GetToursForAuthor", new object[] {
                        AuthorName});
            return ((Tour[])(results[0]));
        }
        
        /// <remarks/>
        public void GetToursForAuthorAsync(string AuthorName) {
            this.GetToursForAuthorAsync(AuthorName, null);
        }
        
        /// <remarks/>
        public void GetToursForAuthorAsync(string AuthorName, object userState) {
            if ((this.GetToursForAuthorOperationCompleted == null)) {
                this.GetToursForAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetToursForAuthorOperationCompleted);
            }
            this.InvokeAsync("GetToursForAuthor", new object[] {
                        AuthorName}, this.GetToursForAuthorOperationCompleted, userState);
        }
        
        private void OnGetToursForAuthorOperationCompleted(object arg) {
            if ((this.GetToursForAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetToursForAuthorCompleted(this, new GetToursForAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetToursForKeyword", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour[] GetToursForKeyword(string Keyword) {
            object[] results = this.Invoke("GetToursForKeyword", new object[] {
                        Keyword});
            return ((Tour[])(results[0]));
        }
        
        /// <remarks/>
        public void GetToursForKeywordAsync(string Keyword) {
            this.GetToursForKeywordAsync(Keyword, null);
        }
        
        /// <remarks/>
        public void GetToursForKeywordAsync(string Keyword, object userState) {
            if ((this.GetToursForKeywordOperationCompleted == null)) {
                this.GetToursForKeywordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetToursForKeywordOperationCompleted);
            }
            this.InvokeAsync("GetToursForKeyword", new object[] {
                        Keyword}, this.GetToursForKeywordOperationCompleted, userState);
        }
        
        private void OnGetToursForKeywordOperationCompleted(object arg) {
            if ((this.GetToursForKeywordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetToursForKeywordCompleted(this, new GetToursForKeywordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://research.microsoft.com/WWT/GetToursForDateRange", RequestNamespace="http://research.microsoft.com/WWT/", ResponseNamespace="http://research.microsoft.com/WWT/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tour[] GetToursForDateRange(string BeginDateTime, string EndDateTime) {
            object[] results = this.Invoke("GetToursForDateRange", new object[] {
                        BeginDateTime,
                        EndDateTime});
            return ((Tour[])(results[0]));
        }
        
        /// <remarks/>
        public void GetToursForDateRangeAsync(string BeginDateTime, string EndDateTime) {
            this.GetToursForDateRangeAsync(BeginDateTime, EndDateTime, null);
        }
        
        /// <remarks/>
        public void GetToursForDateRangeAsync(string BeginDateTime, string EndDateTime, object userState) {
            if ((this.GetToursForDateRangeOperationCompleted == null)) {
                this.GetToursForDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetToursForDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetToursForDateRange", new object[] {
                        BeginDateTime,
                        EndDateTime}, this.GetToursForDateRangeOperationCompleted, userState);
        }
        
        private void OnGetToursForDateRangeOperationCompleted(object arg) {
            if ((this.GetToursForDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetToursForDateRangeCompleted(this, new GetToursForDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // This type definition was generated by System.Data.Design.TypedDataSetSchemaImporterExtension schema importer extension.
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("AstroObjectsDataset")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2549.0")]
    public partial class AstroObjectsDataset : global::System.Data.DataSet {
        
        private spGetAstroObjectsDataTable tablespGetAstroObjects;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public AstroObjectsDataset() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected AstroObjectsDataset(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["spGetAstroObjects"] != null)) {
                    base.Tables.Add(new spGetAstroObjectsDataTable(ds.Tables["spGetAstroObjects"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public spGetAstroObjectsDataTable spGetAstroObjects {
            get {
                return this.tablespGetAstroObjects;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            AstroObjectsDataset cln = ((AstroObjectsDataset)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["spGetAstroObjects"] != null)) {
                    base.Tables.Add(new spGetAstroObjectsDataTable(ds.Tables["spGetAstroObjects"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablespGetAstroObjects = ((spGetAstroObjectsDataTable)(base.Tables["spGetAstroObjects"]));
            if ((initTable == true)) {
                if ((this.tablespGetAstroObjects != null)) {
                    this.tablespGetAstroObjects.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "AstroObjectsDataset";
            this.Prefix = "";
            this.Namespace = "http://research.microsoft.com/WWT/AstroObjectsDataset.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablespGetAstroObjects = new spGetAstroObjectsDataTable();
            base.Tables.Add(this.tablespGetAstroObjects);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializespGetAstroObjects() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            AstroObjectsDataset ds = new AstroObjectsDataset();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void spGetAstroObjectsRowChangeEventHandler(object sender, spGetAstroObjectsRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class spGetAstroObjectsDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnAstroObjectID;
            
            private global::System.Data.DataColumn columnMessierName;
            
            private global::System.Data.DataColumn columnNGCName;
            
            private global::System.Data.DataColumn columnPopularName1;
            
            private global::System.Data.DataColumn columnRa2000;
            
            private global::System.Data.DataColumn columnDec2000;
            
            private global::System.Data.DataColumn columnVisualMagnitude;
            
            private global::System.Data.DataColumn columnConstellationName;
            
            private global::System.Data.DataColumn columnObjectType;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsDataTable() {
                this.TableName = "spGetAstroObjects";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal spGetAstroObjectsDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected spGetAstroObjectsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AstroObjectIDColumn {
                get {
                    return this.columnAstroObjectID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MessierNameColumn {
                get {
                    return this.columnMessierName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NGCNameColumn {
                get {
                    return this.columnNGCName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PopularName1Column {
                get {
                    return this.columnPopularName1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Ra2000Column {
                get {
                    return this.columnRa2000;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Dec2000Column {
                get {
                    return this.columnDec2000;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn VisualMagnitudeColumn {
                get {
                    return this.columnVisualMagnitude;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ConstellationNameColumn {
                get {
                    return this.columnConstellationName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ObjectTypeColumn {
                get {
                    return this.columnObjectType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsRow this[int index] {
                get {
                    return ((spGetAstroObjectsRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event spGetAstroObjectsRowChangeEventHandler spGetAstroObjectsRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event spGetAstroObjectsRowChangeEventHandler spGetAstroObjectsRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event spGetAstroObjectsRowChangeEventHandler spGetAstroObjectsRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event spGetAstroObjectsRowChangeEventHandler spGetAstroObjectsRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddspGetAstroObjectsRow(spGetAstroObjectsRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsRow AddspGetAstroObjectsRow(string MessierName, string NGCName, string PopularName1, double Ra2000, double Dec2000, float VisualMagnitude, string ConstellationName, string ObjectType) {
                spGetAstroObjectsRow rowspGetAstroObjectsRow = ((spGetAstroObjectsRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        MessierName,
                        NGCName,
                        PopularName1,
                        Ra2000,
                        Dec2000,
                        VisualMagnitude,
                        ConstellationName,
                        ObjectType};
                rowspGetAstroObjectsRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowspGetAstroObjectsRow);
                return rowspGetAstroObjectsRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsRow FindByAstroObjectID(long AstroObjectID) {
                return ((spGetAstroObjectsRow)(this.Rows.Find(new object[] {
                            AstroObjectID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                spGetAstroObjectsDataTable cln = ((spGetAstroObjectsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new spGetAstroObjectsDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnAstroObjectID = base.Columns["AstroObjectID"];
                this.columnMessierName = base.Columns["MessierName"];
                this.columnNGCName = base.Columns["NGCName"];
                this.columnPopularName1 = base.Columns["PopularName1"];
                this.columnRa2000 = base.Columns["Ra2000"];
                this.columnDec2000 = base.Columns["Dec2000"];
                this.columnVisualMagnitude = base.Columns["VisualMagnitude"];
                this.columnConstellationName = base.Columns["ConstellationName"];
                this.columnObjectType = base.Columns["ObjectType"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnAstroObjectID = new global::System.Data.DataColumn("AstroObjectID", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAstroObjectID);
                this.columnMessierName = new global::System.Data.DataColumn("MessierName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMessierName);
                this.columnNGCName = new global::System.Data.DataColumn("NGCName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNGCName);
                this.columnPopularName1 = new global::System.Data.DataColumn("PopularName1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPopularName1);
                this.columnRa2000 = new global::System.Data.DataColumn("Ra2000", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRa2000);
                this.columnDec2000 = new global::System.Data.DataColumn("Dec2000", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDec2000);
                this.columnVisualMagnitude = new global::System.Data.DataColumn("VisualMagnitude", typeof(float), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVisualMagnitude);
                this.columnConstellationName = new global::System.Data.DataColumn("ConstellationName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnConstellationName);
                this.columnObjectType = new global::System.Data.DataColumn("ObjectType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnObjectType);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnAstroObjectID}, true));
                this.columnAstroObjectID.AutoIncrement = true;
                this.columnAstroObjectID.AllowDBNull = false;
                this.columnAstroObjectID.ReadOnly = true;
                this.columnAstroObjectID.Unique = true;
                this.columnMessierName.MaxLength = 200;
                this.columnNGCName.MaxLength = 200;
                this.columnPopularName1.MaxLength = 200;
                this.columnConstellationName.MaxLength = 400;
                this.columnObjectType.ReadOnly = true;
                this.columnObjectType.MaxLength = 401;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsRow NewspGetAstroObjectsRow() {
                return ((spGetAstroObjectsRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new spGetAstroObjectsRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(spGetAstroObjectsRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.spGetAstroObjectsRowChanged != null)) {
                    this.spGetAstroObjectsRowChanged(this, new spGetAstroObjectsRowChangeEvent(((spGetAstroObjectsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.spGetAstroObjectsRowChanging != null)) {
                    this.spGetAstroObjectsRowChanging(this, new spGetAstroObjectsRowChangeEvent(((spGetAstroObjectsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.spGetAstroObjectsRowDeleted != null)) {
                    this.spGetAstroObjectsRowDeleted(this, new spGetAstroObjectsRowChangeEvent(((spGetAstroObjectsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.spGetAstroObjectsRowDeleting != null)) {
                    this.spGetAstroObjectsRowDeleting(this, new spGetAstroObjectsRowChangeEvent(((spGetAstroObjectsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovespGetAstroObjectsRow(spGetAstroObjectsRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                AstroObjectsDataset ds = new AstroObjectsDataset();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "spGetAstroObjectsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class spGetAstroObjectsRow : global::System.Data.DataRow {
            
            private spGetAstroObjectsDataTable tablespGetAstroObjects;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal spGetAstroObjectsRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablespGetAstroObjects = ((spGetAstroObjectsDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long AstroObjectID {
                get {
                    return ((long)(this[this.tablespGetAstroObjects.AstroObjectIDColumn]));
                }
                set {
                    this[this.tablespGetAstroObjects.AstroObjectIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MessierName {
                get {
                    try {
                        return ((string)(this[this.tablespGetAstroObjects.MessierNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MessierName\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.MessierNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NGCName {
                get {
                    try {
                        return ((string)(this[this.tablespGetAstroObjects.NGCNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NGCName\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.NGCNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PopularName1 {
                get {
                    try {
                        return ((string)(this[this.tablespGetAstroObjects.PopularName1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PopularName1\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.PopularName1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Ra2000 {
                get {
                    try {
                        return ((double)(this[this.tablespGetAstroObjects.Ra2000Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ra2000\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.Ra2000Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Dec2000 {
                get {
                    try {
                        return ((double)(this[this.tablespGetAstroObjects.Dec2000Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Dec2000\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.Dec2000Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public float VisualMagnitude {
                get {
                    try {
                        return ((float)(this[this.tablespGetAstroObjects.VisualMagnitudeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'VisualMagnitude\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.VisualMagnitudeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ConstellationName {
                get {
                    try {
                        return ((string)(this[this.tablespGetAstroObjects.ConstellationNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ConstellationName\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.ConstellationNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ObjectType {
                get {
                    try {
                        return ((string)(this[this.tablespGetAstroObjects.ObjectTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ObjectType\' in table \'spGetAstroObjects\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespGetAstroObjects.ObjectTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMessierNameNull() {
                return this.IsNull(this.tablespGetAstroObjects.MessierNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMessierNameNull() {
                this[this.tablespGetAstroObjects.MessierNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNGCNameNull() {
                return this.IsNull(this.tablespGetAstroObjects.NGCNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNGCNameNull() {
                this[this.tablespGetAstroObjects.NGCNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPopularName1Null() {
                return this.IsNull(this.tablespGetAstroObjects.PopularName1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPopularName1Null() {
                this[this.tablespGetAstroObjects.PopularName1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRa2000Null() {
                return this.IsNull(this.tablespGetAstroObjects.Ra2000Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRa2000Null() {
                this[this.tablespGetAstroObjects.Ra2000Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDec2000Null() {
                return this.IsNull(this.tablespGetAstroObjects.Dec2000Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDec2000Null() {
                this[this.tablespGetAstroObjects.Dec2000Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsVisualMagnitudeNull() {
                return this.IsNull(this.tablespGetAstroObjects.VisualMagnitudeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetVisualMagnitudeNull() {
                this[this.tablespGetAstroObjects.VisualMagnitudeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsConstellationNameNull() {
                return this.IsNull(this.tablespGetAstroObjects.ConstellationNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetConstellationNameNull() {
                this[this.tablespGetAstroObjects.ConstellationNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsObjectTypeNull() {
                return this.IsNull(this.tablespGetAstroObjects.ObjectTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetObjectTypeNull() {
                this[this.tablespGetAstroObjects.ObjectTypeColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class spGetAstroObjectsRowChangeEvent : global::System.EventArgs {
            
            private spGetAstroObjectsRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsRowChangeEvent(spGetAstroObjectsRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public spGetAstroObjectsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2549.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://research.microsoft.com/WWT/")]
    public partial class Tour {
        
        private System.Guid tourGuidField;
        
        private string tourTitleField;
        
        private string workFlowStatusCodeField;
        
        private System.DateTime tourSubmittedDateTimeField;
        
        private System.DateTime tourApprovedDateTimeField;
        
        private System.DateTime tourRejectedDateTimeField;
        
        private string tourDescriptionField;
        
        private string tourAttributionAndCreditsField;
        
        private string authorNameField;
        
        private string authorEmailAddressField;
        
        private string authorURLField;
        
        private string authorSecondaryEmailAddressField;
        
        private string authorContactPhoneNumberField;
        
        private string authorContactTextField;
        
        private string organizationNameField;
        
        private string organizationURLField;
        
        private string tourKeywordListField;
        
        private string tourAstroObjectListField;
        
        private string tourExplicitTourLinkListField;
        
        private int lengthInSecsField;
        
        private string tourXMLField;
        
        /// <remarks/>
        public System.Guid TourGuid {
            get {
                return this.tourGuidField;
            }
            set {
                this.tourGuidField = value;
            }
        }
        
        /// <remarks/>
        public string TourTitle {
            get {
                return this.tourTitleField;
            }
            set {
                this.tourTitleField = value;
            }
        }
        
        /// <remarks/>
        public string WorkFlowStatusCode {
            get {
                return this.workFlowStatusCodeField;
            }
            set {
                this.workFlowStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TourSubmittedDateTime {
            get {
                return this.tourSubmittedDateTimeField;
            }
            set {
                this.tourSubmittedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TourApprovedDateTime {
            get {
                return this.tourApprovedDateTimeField;
            }
            set {
                this.tourApprovedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TourRejectedDateTime {
            get {
                return this.tourRejectedDateTimeField;
            }
            set {
                this.tourRejectedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TourDescription {
            get {
                return this.tourDescriptionField;
            }
            set {
                this.tourDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TourAttributionAndCredits {
            get {
                return this.tourAttributionAndCreditsField;
            }
            set {
                this.tourAttributionAndCreditsField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorName {
            get {
                return this.authorNameField;
            }
            set {
                this.authorNameField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorEmailAddress {
            get {
                return this.authorEmailAddressField;
            }
            set {
                this.authorEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorURL {
            get {
                return this.authorURLField;
            }
            set {
                this.authorURLField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorSecondaryEmailAddress {
            get {
                return this.authorSecondaryEmailAddressField;
            }
            set {
                this.authorSecondaryEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorContactPhoneNumber {
            get {
                return this.authorContactPhoneNumberField;
            }
            set {
                this.authorContactPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorContactText {
            get {
                return this.authorContactTextField;
            }
            set {
                this.authorContactTextField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationURL {
            get {
                return this.organizationURLField;
            }
            set {
                this.organizationURLField = value;
            }
        }
        
        /// <remarks/>
        public string TourKeywordList {
            get {
                return this.tourKeywordListField;
            }
            set {
                this.tourKeywordListField = value;
            }
        }
        
        /// <remarks/>
        public string TourAstroObjectList {
            get {
                return this.tourAstroObjectListField;
            }
            set {
                this.tourAstroObjectListField = value;
            }
        }
        
        /// <remarks/>
        public string TourExplicitTourLinkList {
            get {
                return this.tourExplicitTourLinkListField;
            }
            set {
                this.tourExplicitTourLinkListField = value;
            }
        }
        
        /// <remarks/>
        public int LengthInSecs {
            get {
                return this.lengthInSecsField;
            }
            set {
                this.lengthInSecsField = value;
            }
        }
        
        /// <remarks/>
        public string TourXML {
            get {
                return this.tourXMLField;
            }
            set {
                this.tourXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetAstroObjectsByRaDecCompletedEventHandler(object sender, GetAstroObjectsByRaDecCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAstroObjectsByRaDecCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAstroObjectsByRaDecCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AstroObjectsDataset Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AstroObjectsDataset)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetAstroObjectsByNameCompletedEventHandler(object sender, GetAstroObjectsByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAstroObjectsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAstroObjectsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AstroObjectsDataset Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AstroObjectsDataset)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetAstroObjectsInCatalogCompletedEventHandler(object sender, GetAstroObjectsInCatalogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAstroObjectsInCatalogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAstroObjectsInCatalogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AstroObjectsDataset Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AstroObjectsDataset)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void ImportTourCompletedEventHandler(object sender, ImportTourCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportTourCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportTourCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void UpdateTourWorkFlowStatusCompletedEventHandler(object sender, UpdateTourWorkFlowStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTourWorkFlowStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTourWorkFlowStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetToursForGUIDCompletedEventHandler(object sender, GetToursForGUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetToursForGUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetToursForGUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetToursForAuthorCompletedEventHandler(object sender, GetToursForAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetToursForAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetToursForAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetToursForKeywordCompletedEventHandler(object sender, GetToursForKeywordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetToursForKeywordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetToursForKeywordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    public delegate void GetToursForDateRangeCompletedEventHandler(object sender, GetToursForDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2549.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetToursForDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetToursForDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tour[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tour[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591